package com.feedthekitty.cmsc436.feedthekitty;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;

import org.w3c.dom.Text;

import com.feedthekitty.cmsc436.feedthekitty.VenmoLibrary;

import android.content.Intent;
import android.widget.Toast;

import org.w3c.dom.Text;

import java.util.ArrayList;

/**
 * Created by Sa on 12/4/2015.
 */
public class EventLayout extends AppCompatActivity implements View.OnClickListener {

    TextView eventName;
    ImageView image;
    TextView moneyRaised;
    TextView description;
    Button donate;
    Button inviteUsers;
    TextView location;
    EventData eventData;

    //Venmo Specific Variables
    private static final int REQUEST_CODE_VENMO_APP_SWITCH = 1;
    private static final String APP_ID = "3248";  //generated by Venmo 4 numbers
    private static final String APP_NAME = "FeedTheKitty";
    private static final String APP_SECRET = "vr7QR9gSEZb8jVuvJs6Xk4SBcr5Cbqnp"; //generated by Venmo

    //Helpful fields for user convenience
    private String eventHostVenmo = "";  //depends on info: Venmo username, phone number, or email
    private String payAmount = "0"; //only need to change if events specify donate amount

    public static final int INVITE_LIST = 5;
    public static final String TAG = "EventLayout";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.event_layout);

        /* Todo Link Each EventData object with this
         * Set variables to hold event data values
         */
        eventData = EventData.createFromIntent(getIntent());
        Log.i(TAG, "Recovered EventData in EventLayout: " + eventData.toString());

        eventName = (TextView) findViewById(R.id.name);
        eventName.setText(eventData.getTitle());

        image = (ImageView) findViewById(R.id.app_image);
        image.setImageBitmap(FirebaseUtils.stringToBitmap(eventData.getEventImage()));

        moneyRaised = (TextView) findViewById(R.id.money_total);
        moneyRaised.setText(eventData.getFunds() + "out of" + eventData.getAmountNeeded());

        Log.d(TAG, eventData.getDescription());
        description = (TextView) findViewById(R.id.event_decription);
        description.setText( eventData.getDescription() );

        donate = (Button) findViewById(R.id.donation);
        donate.setOnClickListener(this);

        inviteUsers = (Button) findViewById(R.id.inviteUsers);
        inviteUsers.setOnClickListener(this);

        location = (TextView) findViewById(R.id.event_location);
        location.setText( eventData.getLocation() );
    }

    @Override
    public void onClick(View view) {
        if (view == donate) {
            //TODO link to Venmo
            if (VenmoLibrary.isVenmoInstalled(getApplicationContext()) == true ) {
                String message = "For event: " + eventName;
                Intent venmoIntent = VenmoLibrary.openVenmoPayment(APP_ID,
                        APP_NAME, eventHostVenmo, payAmount, message, "pay");
                startActivityForResult(venmoIntent, REQUEST_CODE_VENMO_APP_SWITCH);
            } else {
                Toast.makeText(getApplicationContext(), "Please download Venmo from the Google Play Store.",
                        Toast.LENGTH_LONG).show();
            }
        }

        if (view == inviteUsers) {
            Intent intent = new Intent(this, UserSearchActivity.class);
            startActivityForResult(intent, UserSearchActivity.INVITE_LIST);
        }
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data)
    {
        switch(requestCode) {
            case REQUEST_CODE_VENMO_APP_SWITCH: {
                if(resultCode == RESULT_OK) {
                    String signedrequest = data.getStringExtra("signedrequest");
                    if(signedrequest != null) {
                        VenmoLibrary.VenmoResponse response = (new VenmoLibrary()).validateVenmoPaymentResponse(signedrequest, APP_SECRET);
                        if(response.getSuccess().equals("1")) {
                            //Payment successful.  Use data from response object to display a success message
                            String note = response.getNote();
                            String amount = response.getAmount();
                            Toast.makeText(getApplicationContext(), "You successfully paid " + amount + "to "
                                    + eventName, Toast.LENGTH_LONG).show();
                        }
                    }
                    else {
                        String error_message = data.getStringExtra("error_message");
                        //An error ocurred.  Make sure to display the error_message to the user
                        Toast.makeText(getApplicationContext(), "Sorry an uknown error occured.", Toast.LENGTH_LONG).show();
                    }
                }
                else if(resultCode == RESULT_CANCELED) {
                    //The user cancelled the payment
                    Toast.makeText(getApplicationContext(), "Payment Canceled",
                            Toast.LENGTH_LONG).show();
                }
                break;
            }
            case INVITE_LIST: {
                Bundle extras = data.getExtras();
                ArrayList<String> invitedList = (ArrayList<String>)
                        extras.get(UserSearchActivity.INVITED_USERS);

                for (String uid : invitedList) {
                    FirebaseUtils.getInstance().inviteToEvent(uid, eventData.getStackId());
                }
            }
        }
    }
}
